/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/72EX64EfFho
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuCheckboxItem } from "@/components/ui/dropdown-menu"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"

export function ComponentCanvaData() {
  return (
    (<div className="flex flex-col h-screen">
      <header
        className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <DrillIcon className="w-6 h-6" />
          <h1 className="text-2xl font-bold">Drone Damage Analyzer</h1>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon">
            <UploadIcon className="w-5 h-5" />
            <span className="sr-only">Upload Imagery</span>
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon">
                <FilterIcon className="w-5 h-5" />
                <span className="sr-only">Filter Data</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>Filter by:</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuCheckboxItem>Minor Damage</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Moderate Damage</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Severe Damage</DropdownMenuCheckboxItem>
              <DropdownMenuSeparator />
              <DropdownMenuCheckboxItem>Residential</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Commercial</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Industrial</DropdownMenuCheckboxItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <div className="flex-1 grid grid-cols-[1fr_400px] gap-4 p-6">
        <div className="bg-muted rounded-lg overflow-hidden">
          <div className="w-full h-full">
            <div />
            <div />
            <div />
          </div>
        </div>
        <div className="bg-background rounded-lg shadow-lg p-6 overflow-auto">
          <h2 className="text-2xl font-bold mb-4">Building Damage Details</h2>
          <div className="grid gap-4">
            <Card>
              <CardHeader>
                <CardTitle>123 Main St</CardTitle>
                <CardDescription>Residential</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <span>Damage Level:</span>
                  <Badge variant="secondary">Moderate</Badge>
                </div>
                <Separator className="my-4" />
                <div className="flex items-center justify-between">
                  <span>Structural Integrity:</span>
                  <div className="flex items-center gap-2">
                    <BoltIcon className="w-5 h-5 text-yellow-500" />
                    <BoltIcon className="w-5 h-5 text-yellow-500" />
                    <BoltIcon className="w-5 h-5 text-yellow-500" />
                    <BoltIcon className="w-5 h-5 text-gray-400" />
                    <BoltIcon className="w-5 h-5 text-gray-400" />
                  </div>
                </div>
              </CardContent>
              <CardFooter className="flex justify-end">
                <Button variant="outline">Download PDF Assessment</Button>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>456 Oak St</CardTitle>
                <CardDescription>Commercial</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <span>Damage Level:</span>
                  <Badge variant="destructive">Severe</Badge>
                </div>
                <Separator className="my-4" />
                <div className="flex items-center justify-between">
                  <span>Structural Integrity:</span>
                  <div className="flex items-center gap-2">
                    <BoltIcon className="w-5 h-5 text-red-500" />
                    <BoltIcon className="w-5 h-5 text-red-500" />
                    <BoltIcon className="w-5 h-5 text-red-500" />
                    <BoltIcon className="w-5 h-5 text-red-500" />
                    <BoltIcon className="w-5 h-5 text-red-500" />
                  </div>
                </div>
              </CardContent>
              <CardFooter className="flex justify-end">
                <Button variant="outline">Download PDF Assessment</Button>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>789 Elm St</CardTitle>
                <CardDescription>Residential</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <span>Damage Level:</span>
                  <Badge variant="outline">Minor</Badge>
                </div>
                <Separator className="my-4" />
                <div className="flex items-center justify-between">
                  <span>Structural Integrity:</span>
                  <div className="flex items-center gap-2">
                    <BoltIcon className="w-5 h-5 text-green-500" />
                    <BoltIcon className="w-5 h-5 text-green-500" />
                    <BoltIcon className="w-5 h-5 text-green-500" />
                    <BoltIcon className="w-5 h-5 text-green-500" />
                    <BoltIcon className="w-5 h-5 text-green-500" />
                  </div>
                </div>
              </CardContent>
              <CardFooter className="flex justify-end">
                <Button variant="outline">Download PDF Assessment</Button>
              </CardFooter>
            </Card>
          </div>
        </div>
      </div>
    </div>)
  );
}

function BoltIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
      <circle cx="12" cy="12" r="4" />
    </svg>)
  );
}


function DrillIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M14 9c0 .6-.4 1-1 1H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9c.6 0 1 .4 1 1Z" />
      <path d="M18 6h4" />
      <path d="M14 4h3a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-3" />
      <path d="m5 10-2 8" />
      <path d="M12 10v3c0 .6-.4 1-1 1H8" />
      <path d="m7 18 2-8" />
      <path d="M5 22c-1.7 0-3-1.3-3-3 0-.6.4-1 1-1h7c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1Z" />
    </svg>)
  );
}


function FilterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>)
  );
}


function UploadIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>)
  );
}
